### ISSUE TITLE
Wiki 페이지에 프로젝트 관련 용어 정리를 하였습니다.

### ISSUE THREAD

**Issue by udonuin** [jmango61/metadata-about-E-learning-platform#21]
Wiki 페이지에 프로젝트 관련하여 공통으로 필요한 용어들을 정리해보았습니다.
현재는 메타데이터와 교육 관련 메타데이터의 종류를 정리한 상태입니다.
추가 및 수정 해야 하는 부분은 의견을 모아 수정하는 것이 좋을 것 같습니다.

Wiki 페이지 관련 좋은 의견이 있으면 comment 달아주시면 감사하겠습니다.

**Comment by juhyun01** [comment]
수고하셨습니다!
