### ISSUE TITLE
readme 파일의 내용과 관련하여 의견 제시합니다.

### ISSUE THREAD

**Issue by udonuin** [jmango61/metadata-about-E-learning-platform#22]
readme 파일은 깃허브 페이지에 들어오면 가장 먼저 보이는 페이지 이므로
추후 main branch의 readme 파일 내용으로 프로젝트 관련 설명 페이지를 readme 파일에 재삽입하면 좋을 것 같습니다.
아래에는 팀원의 깃허브 주소 등을 삽입하는 것도 좋을 듯 합니다.

**Comment by juhyun01** [comment]
팀원의 깃허브 주소를 삽입하는 것은 좋은 생각인 것 같습니다!

**Comment by jmango61** [comment]
관련 부분 discussions 에서 의논하면 좋을 것 같습니다~!
