### ISSUE TITLE
필요 시 issue와 pull request에 적절한 카테고리의 label을 추가해도 좋을 듯 합니다.

### ISSUE THREAD

**Issue by udonuin** [jmango61/metadata-about-E-learning-platform#23]
issue와 PR이 어떠한 내용을 내포하고 있는지 직관적이고 빠른 파악이 가능하도록
label을 추가하여 카테고리를 분류하는 방법도 좋을 것 같습니다.

label은 기존 github label을 사용하거나 혹은 팀원들이 의견을 모아 필요하다고 생각되는 label을 새로 작성하는 것도 좋을 것 같습니다.

**Comment by juhyun01** [comment]
좋은 생각인 것 같습니다!

**Comment by jmango61** [comment]
label 추가하는 방안 좋은 것 같습니다. 자세한 사항은 Discussions에서 논의하면 좋을 것 같습니다!
