### ISSUE TITLE
Discussions 이용 활성화를 제안합니다.

### ISSUE THREAD

**Issue by juhyun01** [jmango61/metadata-about-E-learning-platform#24]
평소 간단한 용건이나 제안 사항들을 Discussions에서 이야기 하면 좋을 것 같습니다.

**Comment by jmango61** [comment]
동의합니다 ! 제가 Discussions 기능을 오픈하였으니 앞으로 이곳에서 자유롭게 의견 나눴으면 좋겠습니다 ~!

**Comment by udonuin** [comment]
동의합니다. 간단한 용건은 discussions에서 논의하는 것이 좋을 것 같습니다.
