### ISSUE TITLE
EduCOR 온톨로지 패턴 요약에 대한 의견 제시를 부탁드립니다. 

### ISSUE THREAD

**Issue by juhyun01** [jmango61/metadata-about-E-learning-platform#25]
EduCOR 온톨로지의 완전한 스키마를 생성하기 위해 결합될 수 있는 독립적인 모듈이 구성되는데 이 모듈을 패턴이라고 합니다. 
EduCOR 논문을 참고해 패턴 A~G를 요약 정리를 해보았는데 잘못된 내용이나 수정이 필요한 부분이 있다면 의견을 제시해주세요.

**Comment by jmango61** [comment]
요약 정리 해둔 내용 discussions 에 올리시거나 pull requests 에 올려주시면 좋을 것 같습니다 ~!

**Comment by udonuin** [comment]
깔끔하게 잘 정리하신 것 같습니다.
