### ISSUE TITLE
참고 논문입니다. [지능형 학습 시스템을 위한 메타데이터 모형 분석 및 설계 연구, 2011] 

### ISSUE THREAD

**Issue by juhyun01** [jmango61/metadata-about-E-learning-platform#26]
지능형 학습 시스템을 위한 메타데이터 모형 분석 및 설계 연구 
A Study on Analysis and Design of Metadata Model for Intelligent e-Learning System,2011

https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=NPAP09710684&dbt=NPAP

**Comment by jmango61** [comment]
논문 참고하겠습니다~ 좋은 자료 감사합니다 ~!

**Comment by udonuin** [comment]
참고하겠습니다!
