### ISSUE TITLE
(5) 논문 내용에 대해 서로 Q&A 시간을 가졌으면 좋겠습니다.

### ISSUE THREAD

**Issue by jmango61** [jmango61/metadata-about-E-learning-platform#31]
개인적으로 EduCOR 논문 정리를 해보았는데, 명확히 이해가 가지 않는 부분이 있으리라 생각됩니다.

따라서 Discussions 카테고리의 Q&A 기능을 활용하여 
각자 논문 내용 중 어려운 부분을 선택하여 게시글을 남긴 후  comment를 통해 서로 답변 및 피드백을 남겼으면 좋겠습니다 !

**Comment by juhyun01** [comment]
좋은 생각입니다!

**Comment by udonuin** [comment]
좋습니다! 서로 다르게 이해하고 있는 부분은 없는지 확인하는 것도 좋을 듯 합니다
