### ISSUE TITLE
feedback-Discussions & issue...

### ISSUE THREAD

**Issue by Auint** [jmango61/metadata-about-E-learning-platform#33]
Discussions과 issue와 같은 부분에 대해서는
소통 빈도나 간격은 조금 아쉬우나 대체적으로 잘 하고 있습니다.
다만 라벨과 같은 형식으로 분류를 진행하고
PR과 issue 그리고 wiki의 부분끼리 연결해서 진행하면 완벽할 것 같습니다.
(마일스톤 등등 활용할 방안은 많습니다.)

**Comment by jmango61** [comment]
라벨로 분류 진행해보았습니다 ! 
PR과 issue, wiki 부분끼리 연결하는 부분은 곧 팀원들과 의논하여 진행하도록 하겠습니다 ! 
감사합니다 !
