### ISSUE TITLE
feedback-paper summarize

### ISSUE THREAD

**Issue by Auint** [jmango61/metadata-about-E-learning-platform#36]
해석은 잘 하신 거 같으나
요약 부분에서 조금 아쉬운 것 같습니다.
각자 스스로 이 분야에 대해서 모르는 사람에게 발표를 한다고 생각하면서
ppt를 만들거나 정리하시면 완벽할 것 같습니다.

수고하셨습니다.

**Comment by jmango61** [comment]
요약 부분에 있어서는 다시 재수정이 가능하다면 수시로 진행해보도록 하겠습니다 !
ppt를 만들어 정리하면 저도 좋을 것 같다고 생각합니다 !
팀원들과 곧 의논하여 진행해보도록 하겠습니다 !
좋은 의견 감사합니다 !
