### ISSUE TITLE
프로젝트 메인에 표시되는 README 파일의 토대를 작성해 보았습니다.

### ISSUE THREAD

**Issue by udonuin** [jmango61/metadata-about-E-learning-platform#42]
이전에 참여자를 모집할 때 작성했던 Slack 업로드 양식은 새로운 파일을 만들어 [Slack.md](https://github.com/udonuin/metadata-about-E-learning-platform/blob/058756c0bca697570fec3b316f31fb3f1271b998/Slack.md) 로 분류하였습니다. 이전에 작성했던 Slack 양식을 참고하여 README 파일의 초록 작성에 힘을 실어도 좋을 것 같습니다. 아래는 현재까지 진행한 README 파일의 링크 입니다. 토대로써 작성한 것이므로 부족한 부분이 많습니다. 회의 시 수정하여 봅시다.

[README.md](https://github.com/udonuin/metadata-about-E-learning-platform/blob/c86abb274596bb46a4da003c45ecf2ffeafae645/README.md)

**Comment by jmango61** [comment]
확인했습니다. 수고하셨습니다 ~!

**Comment by juhyun01** [comment]
확인했습니다 수고하셨습니다!!
